/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package smartcity;

import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author janet
 */
public class Student extends javax.swing.JInternalFrame {

    /**
     * Creates new form Tourism
     */
    public Student() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui=(BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Unibtn = new javax.swing.JButton();
        Collegebtn = new javax.swing.JButton();
        Nightclubbtn = new javax.swing.JButton();
        Librarybtn = new javax.swing.JButton();

        jLabel1.setText("Student");

        Unibtn.setText("Universities");
        Unibtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UnibtnMouseClicked(evt);
            }
        });

        Collegebtn.setText("Colleges");
        Collegebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CollegebtnMouseClicked(evt);
            }
        });

        Nightclubbtn.setText("Nightclubs");
        Nightclubbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NightclubbtnMouseClicked(evt);
            }
        });

        Librarybtn.setText("Libraries");
        Librarybtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LibrarybtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(383, 383, 383)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Unibtn)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Nightclubbtn)
                                .addGap(136, 136, 136)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Librarybtn)
                                    .addComponent(Collegebtn))))))
                .addContainerGap(544, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(101, 101, 101)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Unibtn)
                    .addComponent(Librarybtn))
                .addGap(111, 111, 111)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Collegebtn)
                    .addComponent(Nightclubbtn))
                .addContainerGap(447, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UnibtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UnibtnMouseClicked
        // TODO add your handling code here:
        UniTable unitable = new UniTable();
    }//GEN-LAST:event_UnibtnMouseClicked

    private void CollegebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CollegebtnMouseClicked
        // TODO add your handling code here:
        UniTable unitable = new UniTable();
    }//GEN-LAST:event_CollegebtnMouseClicked

    private void NightclubbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NightclubbtnMouseClicked
        // TODO add your handling code here:
        NightclubTable nightclubtable = new NightclubTable();
    }//GEN-LAST:event_NightclubbtnMouseClicked

    private void LibrarybtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LibrarybtnMouseClicked
        // TODO add your handling code here:
        LibraryTable librarytable = new LibraryTable();
    }//GEN-LAST:event_LibrarybtnMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Collegebtn;
    private javax.swing.JButton Librarybtn;
    private javax.swing.JButton Nightclubbtn;
    private javax.swing.JButton Unibtn;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
