/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package smartcity;

import javax.swing.*;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.JButton;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author janet
 */
public class Tourism extends javax.swing.JInternalFrame {
    
   

    /**
     * Creates new form Tourism
     */
    public Tourism() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui=(BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Hotelbtn = new javax.swing.JButton();
        Restaurantsbtn = new javax.swing.JButton();
        AttractionsBtn = new javax.swing.JButton();
        Funbtn = new javax.swing.JButton();

        jLabel1.setText("Tourism");

        Hotelbtn.setText("Hotels");
        Hotelbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HotelbtnMouseClicked(evt);
            }
        });
        Hotelbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HotelbtnActionPerformed(evt);
            }
        });

        Restaurantsbtn.setText("Restaurants");
        Restaurantsbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RestaurantsbtnMouseClicked(evt);
            }
        });

        AttractionsBtn.setText("Attractions");
        AttractionsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AttractionsBtnMouseClicked(evt);
            }
        });

        Funbtn.setText("Fun Activites");
        Funbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FunbtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(383, 383, 383)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Hotelbtn)
                            .addComponent(AttractionsBtn))
                        .addGap(99, 99, 99)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Funbtn)
                            .addComponent(Restaurantsbtn))))
                .addContainerGap(544, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Hotelbtn)
                    .addComponent(Restaurantsbtn))
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AttractionsBtn)
                    .addComponent(Funbtn))
                .addContainerGap(501, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HotelbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HotelbtnMouseClicked
        // TODO add your handling code here:
        HotelTable hoteltable = new HotelTable();
        
    }//GEN-LAST:event_HotelbtnMouseClicked
    
    
    private void HotelbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HotelbtnActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_HotelbtnActionPerformed

    private void RestaurantsbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RestaurantsbtnMouseClicked
        // TODO add your handling code here:
        RestaurantsTable restaurantstable = new RestaurantsTable();
    }//GEN-LAST:event_RestaurantsbtnMouseClicked

    private void AttractionsBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AttractionsBtnMouseClicked
        // TODO add your handling code here:
        AttractionsTable attractionstable = new AttractionsTable();
    }//GEN-LAST:event_AttractionsBtnMouseClicked

    private void FunbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FunbtnMouseClicked
        // TODO add your handling code here:
        FunTable funtable = new FunTable();
    }//GEN-LAST:event_FunbtnMouseClicked


    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AttractionsBtn;
    private javax.swing.JButton Funbtn;
    private javax.swing.JButton Hotelbtn;
    private javax.swing.JButton Restaurantsbtn;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
